### ISSUE TITLE
colors messed up on unittest

### ISSUE THREAD

**Issue by graziel666** [0015/ESP32Berry#11]
as the tittle says, i managed to build and upload the unittest sketch, my idea was using it as a base to make something like a serial terminal using the t-deck, but i noticed that the colors are extremely messed up
no matter what, turning on and off the invert colors option at the start it still does the same result
can it be that something changed on the production of the t-deck since this was programmed and now?

https://github.com/0015/ESP32Berry/assets/35145859/ad088422-bbc4-45c8-92db-6fabff3de849

**Comment by AdaSzi** [comment]
Hi, you need to configure LovyanGFX using [lv_conf.h](https://github.com/0015/ESP32Berry/blob/main/LVGL_Setting/lv_conf.h) that is provided in this project. This fixed the issue with colors for me.

**Comment by graziel666** [comment]
> Hi, you need to configure LovyanGFX using [lv_conf.h](https://github.com/0015/ESP32Berry/blob/main/LVGL_Setting/lv_conf.h) that is provided in this project. This fixed the issue with colors for me.

i'm pretty sure i was using it, but maybe is not on the correct folder since i'm flashing it with platformio, i'll give it another  try

**Comment by 0015** [comment]
@AdaSzi Thank you for your comment. @graziel666 Are you still having this issue?

**Comment by graziel666** [comment]
@0015 yup, i just double checked the lv_conf.h and reflashed it, but still the same issue

**Comment by 0015** [comment]
@graziel666 That's interesting. Are you sure you are using LovyanGFX using Arduino_IDE/0_UnitTest_LovyanGFX/LGFX_T-Deck.h ?

**Comment by graziel666** [comment]
@0015 sorry for the late, and yup, just in case i tried to do it using arduinoIde (since i was using platformio until now) to make sure the libs and folders are corret, but still the same result

i thought something may be different with lasts units of the t-deck because i did try another sketches using tft_espi, and had to manually set     tft.invertDisplay(1);

**Comment by 0015** [comment]
@graziel666 Let's try this way. I don't think this is the solution but make sure this is not an issue. 
https://github.com/0015/ESP32Berry/blob/main/Arduino_IDE/0_UnitTest_LovyanGFX/LGFX_T-Deck.h
Line# 46, I set the invert true here. Can you change it to false and then try again?

**Comment by graziel666** [comment]
@0015 just tested it, sadly that also didn't do the trick

**Comment by 0015** [comment]
@graziel666 DId you enable this in lv_conf.h? #define LV_COLOR_16_SWAP 1
I just updated my unit test code. Please check it again. 
![IMG_1607](https://github.com/0015/ESP32Berry/assets/9106382/063baf5d-04f4-4b90-9b8c-37df0ca9fa9f)

**Comment by graziel666** [comment]
success! that last version did the trick
really thanks for the help! and i saw the news about espberry project, cant wait!

![IMG_20240524_114934_574](https://github.com/0015/ESP32Berry/assets/35145859/031f94f6-cbdf-4c3f-8901-427089c45b31)
