### ISSUE TITLE
Issue compiling with Arduino IDE.

### ISSUE THREAD

**Issue by Ian-cmd-ops** [0015/ESP32Berry#12]
In file included from c:\Users\rip_h\OneDrive\Documents\Arduino\libraries\Audio_-_Adafruit_Fork/analyze_fft256.h:31,
                 from c:\Users\rip_h\OneDrive\Documents\Arduino\libraries\Audio_-_Adafruit_Fork/Audio.h:66,
                 from E:\ESP32Berry-main\ESP32Berry-main\Arduino_IDE\ESP32Berry\ESP32Berry_System.hpp:11,
                 from E:\ESP32Berry-main\ESP32Berry-main\Arduino_IDE\ESP32Berry\ESP32Berry.hpp:15,
                 from E:\ESP32Berry-main\ESP32Berry-main\Arduino_IDE\ESP32Berry\ESP32Berry.ino:9:
c:\Users\rip_h\OneDrive\Documents\Arduino\libraries\Audio_-_Adafruit_Fork/AudioStream.h:71:10: fatal error: kinetis.h: No such file or directory
 #include "kinetis.h"
          ^~~~~~~~~~~
compilation terminated.
exit status 1

**Comment by 0015** [comment]
@Ian-cmd-ops This project does not use #include "kinetis.h". Could you try removing the libraries related to this?
