### ISSUE TITLE
[Suggestion] Use a custom bootloader

### ISSUE THREAD

**Issue by WattleFoxxo** [0015/ESP32Berry#13]
Use a custom bootloader/factory-app to load app binaries from separated partitions allowing almost any application to be run.
here is an example I have made made:
https://github.com/WattleFoxxo/TDBoot
https://github.com/WattleFoxxo/TDBoot-Bootloader

**Comment by 0015** [comment]
Very interesting. I will try it when I get the chance. Thank you!
