### ISSUE TITLE
Quick explanation

### ISSUE THREAD

**Issue by richonguzman** [0015/ESP32Berry#2]
Hi,

just got in my hands a T-Deck and would love to help with this, but I need to understand what is the goal and process of this:

first, create a menu for accessing different apps for each thing on the T-Deck?

is this being done on Arduino-ide or in platform ?

**Comment by 0015** [comment]
@richonguzman If I have a chance, I'll create a menu. It's done on Arduino Environment. But I'd like to make the ESP-IDF version as well. (TBA)

**Comment by richonguzman** [comment]
Great , would love to be able to work it like VSCode to add later firmware of the LoRa parts which I already know and work with ;)

**Comment by 0015** [comment]
Let's see how it goes!
