### ISSUE TITLE
please do a step by step installation guide

### ISSUE THREAD

**Issue by richonguzman** [0015/ESP32Berry#3]
hi,

please do a step by step guide :

Macbook Ventura, Arduino IDE 2.1.1 and always library error when trying to compile, before uploading.

So I was wandering what folder . where to install configuration or software

**Comment by 0015** [comment]
Everything needs to be documented, but I need time. Sorry.

1. The first thing you need to do is install libraries T-Deck supports. Without this, the T-Deck will not work.
https://github.com/Xinyuan-LilyGO/T-Deck

2. Before trying my code, please check if T-Deck is working first. 
https://github.com/Xinyuan-LilyGO/T-Deck/tree/master/examples/UnitTest

3. After confirmation, download this ESP32Berry project. If you install LovyanGFX, ChatGPT Client library, it will work normally.
https://github.com/0015/ESP32Berry/tree/main/Arduino_IDE/ESP32Berry

**Comment by richonguzman** [comment]
installed but:

line 386 of ESP32Berry_Display.cpp had to be changed from:

&lv_font_montserrat_20 to &lv_font_montserrat_16 to compile and also it looked like this:
![IMG_2118](https://github.com/0015/ESP32Berry/assets/69999130/a174401e-2a4c-434a-a7a3-abbc7708388c)

**Comment by misterniark** [comment]
Hi Eric and thank you for sharing this code. I learn a lot thanks to you.

I have the same problems with the font and the same graphics results when I compile with lv_font_montserrat_16

**Comment by abdallahnatsheh** [comment]
`tft->begin();
  tft->setRotation(1);
  tft->fillScreen(TFT_BLACK);
  tft->invertDisplay(1);
  this->initLVGL();
}

@@ -41,8 +42,14 @@ void Display::my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color

  tft->startWrite();
  tft->setAddrWindow(area->x1, area->y1, w, h);
  //tft->writePixels((lgfx::rgb565_t *)&color_p->full, w * h);
  tft->pushColors((uint16_t *)&color_p->full, w * h, false);
  tft->endWrite();`
in my fork of this amazing project i managed to fix the bug after i changed write pixels with pushcolors nad use tft->inverdisplay

**Comment by 0015** [comment]
@richonguzman Please use this LVGL config file instead of using the invertDisplay function.  https://github.com/0015/ESP32Berry/blob/main/LVGL_Setting/lv_conf.h

**Comment by richonguzman** [comment]
I did use this , It still with inverted colors and wifi its not working

It would be awesome to have some documentation to know how to add to this and not just create issues  so we could help

**Comment by 0015** [comment]
@richonguzman I don't get it. If you're using the same version as me, it should work without issue.

**Comment by AdaSzi** [comment]
@0015 Hi, it seems like LilyGO changed the screen in some recent revision. The title of this commit is the clue: https://github.com/Xinyuan-LilyGO/T-Deck/commit/386e17731448116cb232e8f9aab235844a878819

While trying to make my T-Deck work I tried Abdallah's solution:

> `tft->begin(); tft->setRotation(1); tft->fillScreen(TFT_BLACK); tft->invertDisplay(1); this->initLVGL(); }
> 
> @@ -41,8 +42,14 @@ void Display::my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color
> 
> tft->startWrite(); tft->setAddrWindow(area->x1, area->y1, w, h); //tft->writePixels((lgfx::rgb565_t *)&color_p->full, w * h); tft->pushColors((uint16_t *)&color_p->full, w * h, false); tft->endWrite();` in my fork of this amazing project i managed to fix the bug after i changed write pixels with pushcolors nad use tft->inverdisplay here is the fork https://github.com/abdallahnatsheh/ESP32Berry

I found out that my unit does not need color inversion `tft->invertDisplay(1);` . Maybe there are 3 different versions of the screen?
I made a pull request https://github.com/0015/ESP32Berry/pull/6 to add this fix as default for users that have newer revision of the T-Deck.
