### ISSUE TITLE
Display black. I could it compile and upload, but the display is black.

### ISSUE THREAD

**Issue by Tinkerpete** [0015/ESP32Berry#5]

**Comment by Tinkerpete** [comment]
I think i have the right lc_conf.h because when i change an command like '#define' the compile progrss breaks. But i have no ideas what i should change for a working display.

**Comment by Tinkerpete** [comment]
Ok, i have it running. But the colors are bad. I could not say what the problem exacly was. But i had worked on the points from T-Desk readme.md. Could be, i had settings wrong.

**Comment by 0015** [comment]
@Tinkerpete Seems like your color setting is inverted. Please try with this lv_conf.h. https://github.com/0015/ESP32Berry/blob/main/LVGL_Setting/lv_conf.h

**Comment by Tinkerpete** [comment]
Now it runs correct! Thank you all!
