### ISSUE TITLE
[App request] Meshtastic 

### ISSUE THREAD

**Issue by Nikguy321** [0015/ESP32Berry#8]
If you are familiar with it, an app for meshtastic would be amazing since that is the number 1 useful thing people use lora for. Meshtastic is awesome but it doesn't really have a UI except for on the phone and web apps. Let me know if you'd like more info!

**Comment by wir19** [comment]
or aprs (on 433 or lora band without ham id) or RNode https://reticulum.network/

**Comment by Ian-cmd-ops** [comment]
It would be a great addition.

**Comment by shaurjyabanerjee** [comment]
agreed! I am currently working on hardware development for the TDeck (better 3D printed case, integrated battery and GPS etc) and I am imagining a version of the ESP32Berry with built in analog UHF Radio, Meshtastic, and more. It could be the ultimate communications device without needing to use any smartphones!

**Comment by 0015** [comment]
Meshtastic officially supports T-Deck, so I tested it. https://youtu.be/wmGBAGr9dNA?si=y-sQVz3bw5J8tQAY
The IDF version of ESP32Berry is being prepared, but it does not seem easy to apply Meshtastic to it. Perhaps it would be wiser to try a custom UI/UX design (Meshtastic code) for the T-Deck.
