### ISSUE TITLE
Not able to get wifi networks to show up

### ISSUE THREAD

**Issue by jeeab** [0015/ESP32Berry#9]
I got the berry OS loaded on my tdeck with working colors etc. However wifi networks aren't showing up. I have both 2.4 and 5ghz wifi in range. Have them pop up visibly once when I was troubleshooting inverted colors but never again. I've reinstalled it a couple times now with no luck.

Hoping for any help

**Comment by AdaSzi** [comment]
It is not so obvious but the wifi is turned off by default. You have to enable it by clicking or touching the WiFi logo (pointed to by the cursor in picture below) Then you will see the wifi networks available
![image](https://github.com/0015/ESP32Berry/assets/81822538/d69f8359-1fa1-4693-a03b-ef447f1e3f9b)

**Comment by 0015** [comment]
@jeeab As @AdaSzi mentioned, you need to turn on the WiFi icon first. Have you tried it?
